# Generated by Django 4.1.7 on 2023-03-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='className',
            field=models.CharField(max_length=255),
        ),
    ]
