# Generated by Django 4.1.7 on 2023-03-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
        migrations.AlterField(
            model_name='user',
            name='className',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
