# Generated by Django 4.1.7 on 2023-03-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_user_is_student_alter_user_classname'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
