# Generated by Django 4.1.7 on 2023-03-25 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_forumpost_course_alter_forumpost_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumPostAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('body', models.CharField(max_length=255, unique=True)),
                ('forum_post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='app.forumpost')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
