# Generated by Django 4.1.7 on 2023-03-25 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_forumpostanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='className',
        ),
    ]
